export type Article = {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  date: string;
  readTime: string;
  image: string;
  imageAlt: string;
  content: string[];
};

// Development catalogue mirrors the approved editorial drafts. Production reads
// from the Supabase repository once the runtime contract is provisioned.
export const articles: Article[] = [
  { slug: 'gaming-monitors-by-setup', title: 'Best Gaming Monitors by Setup, Platform and Desk Size', description: 'Choose a display by constraints—not refresh-rate hype.', category: 'Displays', tags: ['monitors','setup','compatibility'], date: '2026-09-28', readTime: '5 min read', image: '/images/articles/gaming-monitors-by-setup.webp', imageAlt: 'Realistic editorial photograph for gaming monitors by setup', content: ['The right gaming monitor depends on platform, viewing distance, desk depth, GPU output and budget. Start with those constraints before comparing refresh-rate numbers.', 'Check native resolution, supported refresh rate, variable refresh behavior, panel consistency, inputs, stand adjustment, warranty and total cost.', 'Skip the upgrade when the current display already matches the platform output and the proposed replacement solves no stated problem.'] },
  { slug: 'wired-vs-wireless-gaming-headsets', title: 'Wired vs Wireless Gaming Headsets', description: 'Compare charging, compatibility, movement and ownership before choosing.', category: 'Audio', tags: ['headsets','audio','compatibility'], date: '2026-09-28', readTime: '4 min read', image: '/images/articles/wired-vs-wireless-gaming-headsets.webp', imageAlt: 'Realistic editorial photograph for wired versus wireless gaming headsets', content: ['Wired headsets simplify charging and can offer predictable compatibility. Wireless headsets add freedom of movement but also battery, pairing, firmware and receiver variables.', 'Verify the exact connector, receiver, Bluetooth mode, platform support, fit, microphone behavior and replacement parts.', 'Choose wireless when cable freedom is valuable and you accept battery management. Keep the current headset when the real problem is routing, fit or a missing adapter.'] },
  { slug: 'gaming-compatibility-ps5-xbox-pc', title: 'Will This Gaming Accessory Work with PS5, Xbox or PC?', description: 'A compatibility checklist before you spend money on a new accessory.', category: 'Compatibility', tags: ['ps5','xbox','pc'], date: '2026-09-28', readTime: '5 min read', image: '/images/articles/gaming-compatibility-ps5-xbox-pc.webp', imageAlt: 'Realistic editorial photograph of gaming compatibility setup for PS5 Xbox and PC', content: ['Compatibility is a specification check, not a marketing assumption. Start with the platform model, available ports, supported protocols and the exact product variant.', 'Verify connector type, wireless receiver support, software requirements, audio chat behavior and whether a feature is restricted to one platform.', 'Keep the current accessory or choose a universal option when the new device does not solve a clearly stated compatibility problem.'] },
  { slug: 'mechanical-keyboard-gaming-work', title: 'Mechanical Keyboards for Gaming and Work', description: 'Choose layout, switch feel and connectivity for two different jobs.', category: 'Peripherals', tags: ['keyboard','work','switches'], date: '2026-09-28', readTime: '5 min read', image: '/images/articles/mechanical-keyboard-gaming-work.webp', imageAlt: 'Realistic editorial photograph of a mechanical keyboard on a gaming and work desk', content: ['A keyboard used for gaming and work has two jobs: predictable input and comfortable long-form use. Layout, key spacing, sound and connection should be evaluated together.', 'Compare the physical layout, switch feel, firmware behavior, wired and wireless modes, operating-system support and replacement parts.', 'Do not upgrade for switch terminology alone. Try the current keyboard with better positioning or keycaps first when the actual issue is comfort.'] },
  { slug: '1080p-vs-1440p-gaming', title: '1080p vs 1440p Gaming', description: 'Understand the practical trade-offs before changing resolution.', category: 'Displays', tags: ['1080p','1440p','resolution'], date: '2026-09-28', readTime: '5 min read', image: '/images/articles/1080p-vs-1440p-gaming.webp', imageAlt: 'Realistic editorial photograph comparing 1080p and 1440p gaming displays', content: ['Resolution changes image detail and rendering demand. The useful choice depends on viewing distance, screen size, GPU output and the games you actually play.', 'Compare the native resolution, target frame rate, scaling behavior, desk depth and connection standard before treating a higher number as an automatic upgrade.', 'Keep 1080p when it already matches the platform and performance target. A resolution change should solve a visible problem, not just follow a specification trend.'] },
  { slug: 'clean-gaming-desk-small-rooms', title: 'Clean Gaming Desk Setup for Small Rooms', description: 'Improve organization and aesthetics while preserving function.', category: 'Setup', tags: ['desk','small-space','organization'], date: '2026-09-28', readTime: '4 min read', image: '/images/articles/clean-gaming-desk-small-rooms.webp', imageAlt: 'Editorial illustration for clean gaming desk small rooms', content: ['Small rooms benefit from prioritizing clear reach zones, cable routing and flexible placement before decorative accessories.', 'Measure the desk, monitor footprint, chair clearance and power path. Use vertical storage and reversible organization where possible.', 'Skip a new desk when moving the display, removing unused hardware or routing cables already solves the problem.'] },
  { slug: 'what-refresh-rate-means', title: 'What Refresh Rate Actually Means for Gaming', description: 'Understand what refresh rate can and cannot change.', category: 'Displays', tags: ['refresh-rate','performance','monitors'], date: '2026-09-28', readTime: '4 min read', image: '/images/articles/what-refresh-rate-means.webp', imageAlt: 'Editorial illustration for what refresh rate means', content: ['Refresh rate describes how often a display can update, while the platform and game determine what signal is available.', 'Check the complete chain: game output, GPU or console support, cable standard, display input and variable-refresh behavior.', 'A higher maximum does not guarantee a better experience if the system cannot produce or sustain the relevant output.'] },
  { slug: 'gaming-desk-ergonomics-basics', title: 'Gaming Desk Ergonomics Basics Without Medical Claims', description: 'General comfort principles for arranging a gaming desk.', category: 'Setup', tags: ['ergonomics','comfort','desk'], date: '2026-09-28', readTime: '4 min read', image: '/images/articles/gaming-desk-ergonomics-basics.webp', imageAlt: 'Editorial illustration for gaming desk ergonomics basics', content: ['Comfort starts with adjustability and regular variation, not a single expensive accessory. Place the display at a comfortable distance and keep frequently used inputs within easy reach.', 'Organize cables and lighting so they do not create avoidable distractions. Take breaks and change position during long sessions.', 'This is general educational guidance, not medical advice. Seek a qualified professional for persistent pain or a health concern.'] },
  { slug: 'gaming-setup-three-budgets', title: 'Gaming Setup Essentials: Three Budget Priorities', description: 'Allocate a setup budget around problems, not a shopping list.', category: 'Setup', tags: ['budget','beginner','setup'], date: '2026-09-28', readTime: '5 min read', image: '/images/articles/gaming-setup-three-budgets.webp', imageAlt: 'Editorial illustration for gaming setup three budgets', content: ['A budget setup should be planned in priorities: reliable platform and display, usable input and audio, then comfort and organization.', 'At every budget, define the problem first and verify compatibility before adding accessories. Existing equipment may cover one category already.', 'The best saving is skipping a purchase that does not change the real use case.'] },
  { slug: 'gaming-setup-essentials-for-beginners', title: 'Gaming Setup Essentials for Beginners', description: 'Build around platform, space and the problem you actually need to solve.', category: 'Setup', tags: ['beginner','setup','budget'], date: '2026-09-28', readTime: '4 min read', image: '/images/articles/gaming-setup-essentials-for-beginners.webp', imageAlt: 'Editorial illustration for gaming setup essentials for beginners', content: ['A useful first setup begins with the platform, available space, existing equipment and the problem to solve.', 'Build in this order: platform and display; input and audio; comfort and organization; style.', 'Use what you already own when possible. Skip a purchase when it solves no clearly stated problem.'] },
];

export function getArticle(slug: string) { return articles.find(article => article.slug === slug); }
export function categories() { return [...new Set(articles.map(article => article.category))]; }
